---
title: "Discussion_3"
output:
  html_document: default
---

```{r}
library(dplyr)
library(caTools) # for sample.split
library(PRROC) # for ROC
j ```

```{r}
# Reading and splitting data
loans <- read.csv("loans.csv")
head(loans)
# Set a seed so we all get the same split
set.seed(144)
```

```{r}
# sample.split splits the dataset smartly for binary outcomes:
# it keeps the same ratio defaulated/not defaulted in the train and test sets (first argument)
# SplitRatio = 0.7 means that we will put 70% of the data in the training, 30% in the testing
split = sample.split(loans$not.fully.paid, SplitRatio = 0.7)
split
# what is a split?
loans.train <- filter(loans, split == TRUE) # is split a variable in loans?
loans.test <- filter(loans, split == FALSE)

# How many loans have defaulted?
table(loans.train$not.fully.paid)
table(loans.test$not.fully.paid)
```

```{r}
# Baseline model: predict that no one defaults
# Accuracy of baseline on training:
5596/(5596 + 1065)
# 0.84% of ratio of loans not fully paid


# Your turn: Accuracy of baseline on testing:
2399/(2399 + 456)

# What is the TPR and FPR of the baseline?
 # 0.84%

```
```{r}
# Fit the logistic regression model
# Notice glm instead of lm
mod <- glm(not.fully.paid ~ installment + log.annual.inc + fico + revol.bal + inq.last.6mths + pub.rec, data=loans.train, family="binomial")
summary(mod)
```
```{r}
# Predictions on the test set 
predTest = predict(mod, newdata=loans.test, type="response")
# If you don't include "type="response"", then predTest will
# return -(b0 + b1*x1 + b2*x2 +...).
# Values could range from -Inf to +Inf.
summary(predTest)
```

```{r}
# Now, create the confusion matrix with threshold probability = 0.5.
table(loans.test$not.fully.paid, predTest > 0.5)
# What is the accuracy?
(2390+9)/(447+9+2390+9)

# What is the True Positive Rate ?
(12/(12+444))
 # = 2.6%

# What is the False Positive rate ?
12/(12+2387)
# = 0.5%
```

```{r}
# Now, try threshold probability = 0.2.
table(loans.test$not.fully.paid, predTest > 0.2)
# What is the accuracy?
# What is the True Positive Rate ?
# What is the False Positive rate ?

```

```{r}
# Some ROC packages in R
# ROCR, pROC, PRROC, plotROC, precrec, ROCit

# Take PRROC as an example
PRROC_obj <- roc.curve(scores.class0 = predTest, weights.class0 = loans.test$not.fully.paid, curve=TRUE)
plot(PRROC_obj)
```
